### ISSUE TITLE
SourceAnnotationExtractor deprecation warning on Rails 6

### ISSUE THREAD

**Issue by benny-burkhart** [willbryant/table_display#3]
When upgrading a rails app that uses table_display to Rails 6, a deprecation warning regarding SourceAnnotationExtractor was issued.

Research found [the injection of module TableDisplay](https://github.com/willbryant/table_display/blob/f997b47/lib/table_display.rb#L118) at fault. Consensus here is that this looks both intrusive and unnecessary.

Opening PR #2 for this -- @willbryant can you please have a look? Thanks!

**Comment by willbryant** [comment]
What was the deprecation message?

**Comment by benny-burkhart** [comment]
`DEPRECATION WARNING: SourceAnnotationExtractor is deprecated! Use Rails::SourceAnnotationExtractor instead. (called from <main> at /an/app/config/application.rb:51)`

That line is a standard `Bundler.require(*Rails.groups) if defined?(Bundler)`.

The warning originates in [source_annotation_extractor in rails](https://github.com/rails/rails/blob/v6.0.2.1/railties/lib/rails/source_annotation_extractor.rb#L159).

**Comment by willbryant** [comment]
OK, not sure why I don't get this when I run the test suite, but seems annoying.

The root of the issue here is me trying to be too fancy with my Enumerable monkeypatching.

I'm not particularly opposed to the approach in pull request #2.  But it's not backwards compatible so I'd want to introduce the new class method API in one release and then do a major version bump to remove it.

There's a simpler solution in the meantime, which is just to cut out my unnecessary fanciness and patch Enumerable directly.

**Comment by willbryant** [comment]
Could you please try 2.2.0 and reopen this incident if not fixed?
